name: build-release
on:
  push:
    branches:
      - '**'
    paths:
      - 'templates/**'
      - 'ui/**'
      - 'app.py'
      - 'api.py'
  pull_request:
    paths:
      - 'templates/**'
      - 'ui/**'
      - 'app.py'
      - 'api.py'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python: ['3.11']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            pyinstaller --clean -y --target-arch universal2 app.spec
          else
            pyinstaller --clean -y app.spec
          fi

      # Additional macOS build for older Intel Macs (x86_64)
      - name: Build macOS x86_64 (PyInstaller)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --clean -y --target-arch x86_64 --distpath dist-x64 --workpath build-x64 app.spec

      # --- Windows packaging (ZIP using PowerShell Compress-Archive) ---
      - name: Package Windows (ZIP)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          if (Test-Path 'dist\FormGen-windows.zip') { Remove-Item 'dist\FormGen-windows.zip' -Force }
          $dir = 'dist\\SDDL-DS'
          $exe = 'dist\\SDDL-DS.exe'
          if (Test-Path $dir) {
            Compress-Archive -Path $dir -DestinationPath 'dist\SDDL-DS-windows.zip' -Force
          } elseif (Test-Path $exe) {
            Compress-Archive -Path $exe -DestinationPath 'dist\SDDL-DS-windows.zip' -Force
          } else {
            Get-ChildItem dist -Recurse | Format-List -Force | Out-String | Write-Output
            throw "PyInstaller output not found: expected 'dist\\SDDL-DS' or 'dist\\SDDL-DS.exe'"
          }

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: dist/SDDL-DS-windows.zip

      # --- macOS packaging (DMG via hdiutil) ---
      - name: Package macOS (DMG)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          set -euxo pipefail
          APP_DIR="./dist/SDDL-DS.app"
          if [ ! -e "$APP_DIR" ]; then
            # Fallback: if PyInstaller emitted onedir without BUNDLE, try folder
            ALT_APP="./dist/SDDL-DS"
            if [ -d "$ALT_APP" ]; then APP_DIR="$ALT_APP"; else ls -laR ./dist; echo "No FormGen.app found"; exit 1; fi
          fi
          hdiutil create -volname 'SDDL-DS' -srcfolder "$APP_DIR" -ov -format UDZO 'dist/SDDL-DS-macos.dmg'

      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-artifact
          path: dist/SDDL-DS-macos.dmg

      # Package Intel-only DMG from x64 dist
      - name: Package macOS x86_64 (DMG)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          set -euxo pipefail
          APP_DIR_X64="./dist-x64/SDDL-DS.app"
          if [ ! -e "$APP_DIR_X64" ]; then
            ALT_APP_X64="./dist-x64/SDDL-DS"
            if [ -d "$ALT_APP_X64" ]; then APP_DIR_X64="$ALT_APP_X64"; else ls -laR ./dist-x64 || true; echo "No SDDL-DS.app in dist-x64"; exit 1; fi
          fi
          hdiutil create -volname 'SDDL-DS' -srcfolder "$APP_DIR_X64" -ov -format UDZO 'dist/SDDL-DS-macos-x64.dmg'

      - name: Upload macOS x86_64 artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-x64-artifact
          path: dist/SDDL-DS-macos-x64.dmg

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/SDDL-DS-windows.zip
            artifacts/**/SDDL-DS-macos.dmg
            artifacts/**/SDDL-DS-macos-x64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
